// Uzhavar Mutram - Comprehensive Multi-Language Dictionary & South Indian Market Registry
// Uzhavar Mutram - Comprehensive Multi-Language Dictionary & South Indian Market Registry

const CROPS = [
  {
    id: "PADDY_PONNI",
    category: "Cereals",
    nameEn: "Ponni Paddy / Rice (Grade A)",
    nameTa: "பொன்னி நெல் / அரிசி (முதல் தரம்)",
    nameHi: "पोन्नी धान / चावल (ग्रेड A)",
    nameTe: "పొన్ని వరి / బియ్యం (గ్రేడ్ A)",
    nameMl: "പൊന്നി നെല്ല് / അരി (ഗ്രേഡ് A)",
    nameKn: "ಪೊನ್ನಿ ಭತ್ತ / ಅಕ್ಕಿ (ಗ್ರೇಡ್ A)",
    mspPerQuintal: 2300,
    pricePerKg: 25.50,
    dailyArrivalTonnes: 450,
    priceTrend: "+2.5%",
    highestPriceKg: 27.50,
    minPriceKg: 24.00,
    demandStatus: "High Demand",
    qualityGrade: "Export Quality Premium",
    imageUrl: "public/images/crops/ponni-paddy-rice.jpeg",
    imageCredit: "Ponni Paddy / Rice (Grade A) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "PADDY_SEERAGA_SAMBA",
    category: "Cereals",
    nameEn: "Seeraga Samba Paddy (Biryani Special)",
    nameTa: "சீரக சம்பா நெல் (பிரியாணி சிறப்பு)",
    nameHi: "सीरगा साम्बा धान (बिरयानी विशेष)",
    nameTe: "సీరగా సాంబ వరి (బిర్యానీ స్పెషల్)",
    nameMl: "സീരഗ സമ്പ നെല്ല് (ബിരിയാണി സ്പെഷ്യൽ)",
    nameKn: "ಸೀರಗ ಸಾಂಬ ಭತ್ತ (ಬಿರಿಯಾನಿ ಸ್ಪೆಷಲ್)",
    mspPerQuintal: 4800,
    pricePerKg: 52.00,
    dailyArrivalTonnes: 180,
    priceTrend: "+4.8%",
    highestPriceKg: 58.00,
    minPriceKg: 48.00,
    demandStatus: "Super Premium Demand",
    qualityGrade: "Heritage Organic Grade",
    imageUrl: "public/images/crops/seeraga-samba-paddy.jpeg",
    imageCredit: "Seeraga Samba Paddy (Biryani Special) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "WHEAT",
    category: "Cereals",
    nameEn: "Sharbati Wheat (Grade A)",
    nameTa: "சார்பாட்டி கோதுமை (தரம் A)",
    nameHi: "शारबती गेहूं (ग्रेड A)",
    nameTe: "షార్బతి గోధుమ (గ్రేడ్ A)",
    nameMl: "ഷാർബതി ഗോതമ്പ് (ഗ്രേഡ് A)",
    nameKn: "ಶಾರ್ಬತಿ ಗೋಧಿ (ಗ್ರೇಡ್ A)",
    mspPerQuintal: 2275,
    pricePerKg: 24.50,
    dailyArrivalTonnes: 120,
    priceTrend: "+2.1%",
    highestPriceKg: 26.00,
    minPriceKg: 23.00,
    demandStatus: "High Demand",
    qualityGrade: "Super Grade",
    imageUrl: "public/images/crops/sharbati-wheat.jpeg",
    imageCredit: "Sharbati Wheat (Grade A) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "SUGARCANE",
    category: "Cash Crops",
    nameEn: "Sugarcane (High Sucrose FRP)",
    nameTa: "கரும்பு (அதிக சர்க்கரை FRP)",
    nameHi: "गन्ना (उच्च सुक्रोज FRP)",
    nameTe: "చెరకు (అధిక షుగర్ FRP)",
    nameMl: "കരിമ്പ് (ഹൈ സുക്രോസ് FRP)",
    nameKn: "ಕಬ್ಬು (ಹೈ ಸುಕ್ರೋಸ್ FRP)",
    mspPerQuintal: 340,
    pricePerKg: 3.40,
    dailyArrivalTonnes: 1200,
    priceTrend: "+0.6%",
    highestPriceKg: 3.60,
    minPriceKg: 3.15,
    demandStatus: "FRP Guaranteed",
    qualityGrade: "High Sucrose Mills Grade",
    imageUrl: "public/images/crops/sugarcane.jpeg",
    imageCredit: "Sugarcane (High Sucrose FRP) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "TEA_LEAF",
    category: "Cash Crops",
    nameEn: "Green Tea Leaves (Nilgiris Special)",
    nameTa: "தேயிலை (நீலகிரி ஸ்பெஷல்)",
    nameHi: "चाय की पत्ती (नीलगिरि विशेष)",
    nameTe: "తేయాకు (నీలగిరి ప్రత్యేక)",
    nameMl: "തേയില (നീലഗിരി സ്പെഷ്യൽ)",
    nameKn: "ಟೀ ಎಲೆ (ನೀಲಗಿರಿ ಸ್ಪೆಷಲ್)",
    mspPerQuintal: 2400,
    pricePerKg: 24.00,
    dailyArrivalTonnes: 190,
    priceTrend: "+1.9%",
    highestPriceKg: 27.50,
    minPriceKg: 22.00,
    demandStatus: "Stable",
    qualityGrade: "Two Leaves & Bud",
    imageUrl: "public/images/crops/green-tea-leaves.jpeg",
    imageCredit: "Green Tea Leaves (Nilgiris Special) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "MANGO_ALPHONSO",
    category: "Fruits & Vegetables",
    nameEn: "Mango (Salem Alphonso / Malgova)",
    nameTa: "மாம்பழம் (சேலம் அல்போன்சா / மல்கோவா)",
    nameHi: "आम (सेलम अलफोंसो / मलगोवा)",
    nameTe: "మామిడిపండు (సేలం అల్ఫోన్సో / మల్గోవా)",
    nameMl: "മാമ്പഴം (സേലം അൽഫോൺസോ / മൽഗോവ)",
    nameKn: "ಮಾವಿನಹಣ್ಣು (ಸೇಲಂ ಅಲ್ಫೋನ್ಸೊ / ಮಲ್ಗೋವಾ)",
    mspPerQuintal: 4500,
    pricePerKg: 52.00,
    dailyArrivalTonnes: 150,
    priceTrend: "+6.5%",
    highestPriceKg: 65.00,
    minPriceKg: 45.00,
    demandStatus: "Seasonal Peak",
    qualityGrade: "Grade A Sweet",
    imageUrl: "public/images/crops/mango-salem-alphonso.jpeg",
    imageCredit: "Mango (Salem Alphonso / Malgova) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "BANANA_NENDRAN",
    category: "Fruits & Vegetables",
    nameEn: "Banana (Theni Nendran / Yelakki)",
    nameTa: "வாழைப்பழம் (தேனி நேந்திரம் / ஏலக்கி)",
    nameHi: "केला (थेनी नेंद्रन / एलक्की)",
    nameTe: "అరటిపండు (తేని నేంద్రన్ / యెలక్కి)",
    nameMl: "നേന്ത്രപ്പഴം / ഏലക്കി (തേനി)",
    nameKn: "ಬಾಳೆಹಣ್ಣು (ತೇನಿ ನೇಂದ್ರನ್ / ಯೆಳಕ್ಕಿ)",
    mspPerQuintal: 2800,
    pricePerKg: 32.00,
    dailyArrivalTonnes: 210,
    priceTrend: "+4.0%",
    highestPriceKg: 38.00,
    minPriceKg: 28.00,
    demandStatus: "High Demand",
    qualityGrade: "Premium Bunch",
    imageUrl: "public/images/crops/banana-theni-nendran.jpeg",
    imageCredit: "Banana (Theni Nendran / Yelakki) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "TOMATO",
    category: "Fruits & Vegetables",
    nameEn: "Fresh Farm Tomato (Oddanchatram)",
    nameTa: "தக்காளி (ஒட்டன்சத்திரம்)",
    nameHi: "टमाटर (ओड्डनछत्रम)",
    nameTe: "టమాటా (ఒడ్డంచత్రం)",
    nameMl: "തക്കാളി (ഒട്ടൻചത്രം)",
    nameKn: "ಟಮಾಟೊ (ಒಡ್ಡಂಚತ್ರಂ)",
    mspPerQuintal: 1800,
    pricePerKg: 22.00,
    dailyArrivalTonnes: 380,
    priceTrend: "+8.5%",
    highestPriceKg: 28.00,
    minPriceKg: 18.00,
    demandStatus: "Volatile Demand",
    qualityGrade: "Fresh Farm Grade A",
    imageUrl: "public/images/crops/fresh-farm-tomato.jpeg",
    imageCredit: "Fresh Farm Tomato (Oddanchatram) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "SHALLOTS_ONION",
    category: "Fruits & Vegetables",
    nameEn: "Small Shallots (Perambalur / Trichy Red)",
    nameTa: "சின்ன வெங்காயம் (பெரம்பலூர் / திருச்சி சிகப்பு)",
    nameHi: "छोटा प्याज (पेराम्बलूर / त्रिची लाल)",
    nameTe: "చిన్న ఉల్లిపాయలు (పెరంబలూర్ / త్రిచీ రెడ్)",
    nameMl: "ചെറിയ ഉള്ളി (പെരമ്പലൂർ / തൃശ്ശൂർ റെഡ്)",
    nameKn: "ಚಿಕ್ಕ ಈರುಳ್ಳಿ (ಪೆರಂಬಲೂರ್ / ತಿರುಚಿ ರೆಡ್)",
    mspPerQuintal: 3500,
    pricePerKg: 42.00,
    dailyArrivalTonnes: 260,
    priceTrend: "+5.1%",
    highestPriceKg: 48.00,
    minPriceKg: 36.00,
    demandStatus: "Very High Demand",
    qualityGrade: "Grade A Red Shallots",
    imageUrl: "public/images/crops/small-shallots-trichy-red.jpeg",
    imageCredit: "Small Shallots (Perambalur / Trichy Red) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "COCONUT_COPRA",
    category: "Cash Crops",
    nameEn: "Coconut & Dried Copra (Pollachi)",
    nameTa: "தேங்காய் & கொப்பரை (பொள்ளாச்சி)",
    nameHi: "नारियल और खोपरा (पोल्लाची)",
    nameTe: "కొబ్బరికాయ / కొబ్బరి (పొల్లాచి)",
    nameMl: "തേങ്ങ / കൊപ്ര (പൊള്ളാച്ചി)",
    nameKn: "ತೆಂಗಿನಕಾಯಿ / ಕೊಬ್ಬರಿ (ಪೊಳ್ಳಾಚಿ)",
    mspPerQuintal: 10860,
    pricePerKg: 115.00,
    dailyArrivalTonnes: 310,
    priceTrend: "+3.2%",
    highestPriceKg: 125.00,
    minPriceKg: 108.00,
    demandStatus: "High Demand",
    qualityGrade: "Grade A Copra",
    imageUrl: "public/images/crops/coconut-copra-pollachi.jpeg",
    imageCredit: "Coconut & Dried Copra (Pollachi) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "RED_CHILLI",
    category: "Spices",
    nameEn: "Red Chilli (Ramnad Mundu / Guntur)",
    nameTa: "சிவப்பு மிளகாய் (இராமநாதபுரம் குண்டு / குண்டூர்)",
    nameHi: "लाल मिर्च (रामनाड मुंडू / गुंटूर)",
    nameTe: "ఎండు మిర్చి (రామనాథపురం గుండు / గుంటూరు)",
    nameMl: "വറ്റൽ മുളക് (രാമനാട് മുണ്ട് / ഗുണ്ടൂർ)",
    nameKn: "ಒಣ ಮೆಣಸಿನಕಾಯಿ (ರಾಮನಾಡ ಮುಂಡು / ಗುಂಟೂರು)",
    mspPerQuintal: 12500,
    pricePerKg: 145.00,
    dailyArrivalTonnes: 140,
    priceTrend: "+4.8%",
    highestPriceKg: 160.00,
    minPriceKg: 135.00,
    demandStatus: "High Demand",
    qualityGrade: "Ramnad Mundu Premium",
    imageUrl: "public/images/crops/red-chilli-ramnad-mundu.jpeg",
    imageCredit: "Red Chilli (Ramnad Mundu / Guntur) — farmer-supplied photo",
    imageSourceUrl: ""
  },
  {
    id: "TURMERIC",
    category: "Spices",
    nameEn: "Turmeric (Erode Finger Special)",
    nameTa: "மஞ்சள் (ஈரோடு ஸ்பெஷல் விரல் மஞ்சள்)",
    nameHi: "हल्दी (ईरोड विशेष)",
    nameTe: "పసుపు (ఈరోడ్ స్పెషల్)",
    nameMl: "മഞ്ഞൾ (ഈറോഡ് സ്പെഷ്യൽ)",
    nameKn: "ಅರಶಿನ (ಈರೋಡ್ ಸ್ಪೆಷಲ್)",
    mspPerQuintal: 8500,
    pricePerKg: 98.00,
    dailyArrivalTonnes: 220,
    priceTrend: "+6.2%",
    highestPriceKg: 110.00,
    minPriceKg: 90.00,
    demandStatus: "Export Peak Demand",
    qualityGrade: "Finger Grade A Gold",
    imageUrl: "public/images/crops/turmeric-erode-finger.jpeg",
    imageCredit: "Turmeric (Erode Finger Special) — farmer-supplied photo",
    imageSourceUrl: ""
  }
];

const MANDI_CENTRES = [
  { id: "MND-01", name: "Koyambedu Wholesale Market Complex", district: "Chennai", state: "Tamil Nadu", address: "Koyambedu, Chennai, Tamil Nadu - 600107", capacityPerDayQuintals: 25000, dailyBookingsCount: 42, activeDockCount: 16, officerInCharge: "Shri V. Muthukumar", phone: "+91 44 2479 1000" },
  { id: "MND-02", name: "Madurai Mattuthavani Regulated Market Hub", district: "Madurai", state: "Tamil Nadu", address: "Mattuthavani, Madurai, Tamil Nadu - 625007", capacityPerDayQuintals: 18000, dailyBookingsCount: 31, activeDockCount: 12, officerInCharge: "Shri M. Perumal", phone: "+91 452 253 1120" },
  { id: "MND-03", name: "Oddanchatram Vegetable & Grain Market", district: "Dindigul", state: "Tamil Nadu", address: "Market Road, Oddanchatram, Tamil Nadu - 624619", capacityPerDayQuintals: 22000, dailyBookingsCount: 38, activeDockCount: 14, officerInCharge: "Shri S. Subramanian", phone: "+91 4553 241 005" },
  { id: "MND-04", name: "Erode Agricultural Producers Co-op Market", district: "Erode", state: "Tamil Nadu", address: "Karur Bypass Road, Erode, Tamil Nadu - 638002", capacityPerDayQuintals: 20000, dailyBookingsCount: 29, activeDockCount: 10, officerInCharge: "Smt. P. Selvi", phone: "+91 424 225 8901" },
  { id: "MND-05", name: "Tirupur Regulated Market Yard", district: "Tirupur", state: "Tamil Nadu", address: "Cotton Market Complex, Tirupur, Tamil Nadu - 641604", capacityPerDayQuintals: 16000, dailyBookingsCount: 22, activeDockCount: 8, officerInCharge: "Shri K. Rajendran", phone: "+91 421 220 3344" },
  { id: "MND-06", name: "Salem APMC Regulated Market Yard", district: "Salem", state: "Tamil Nadu", address: "Ammapet Main Road, Salem, Tamil Nadu - 636003", capacityPerDayQuintals: 17500, dailyBookingsCount: 25, activeDockCount: 10, officerInCharge: "Shri R. Loganathan", phone: "+91 427 226 7788" },
  { id: "MND-07", name: "Trichy Gandhi Market Yard", district: "Tiruchirappalli", state: "Tamil Nadu", address: "East Boulevard Road, Trichy, Tamil Nadu - 620008", capacityPerDayQuintals: 19000, dailyBookingsCount: 27, activeDockCount: 11, officerInCharge: "Shri T. Sundaram", phone: "+91 431 270 4455" },
  { id: "MND-08", name: "Thanjavur Grain Collection Centre", district: "Thanjavur", state: "Tamil Nadu", address: "Paddy Complex, Thanjavur, Tamil Nadu - 613001", capacityPerDayQuintals: 21000, dailyBookingsCount: 35, activeDockCount: 12, officerInCharge: "Shri N. Ilango", phone: "+91 4362 231 190" },
  { id: "MND-09", name: "Vellore APMC Market Yard", district: "Vellore", state: "Tamil Nadu", address: "Katpadi Road, Vellore, Tamil Nadu - 632004", capacityPerDayQuintals: 14000, dailyBookingsCount: 19, activeDockCount: 8, officerInCharge: "Smt. G. Vasanthi", phone: "+91 416 222 5566" },
  { id: "MND-10", name: "Tirunelveli Regulated Market Yard", district: "Tirunelveli", state: "Tamil Nadu", address: "Vannarpettai, Tirunelveli, Tamil Nadu - 627003", capacityPerDayQuintals: 15500, dailyBookingsCount: 21, activeDockCount: 9, officerInCharge: "Shri A. Shanmugam", phone: "+91 462 250 1234" },
  { id: "MND-11", name: "Pollachi Coconut & Spices Market", district: "Coimbatore", state: "Tamil Nadu", address: "Palani Road, Pollachi, Tamil Nadu - 642001", capacityPerDayQuintals: 18500, dailyBookingsCount: 30, activeDockCount: 10, officerInCharge: "Shri C. Velusamy", phone: "+91 4259 223 900" },
  { id: "MND-12", name: "Cuddalore Agricultural Market Yard", district: "Cuddalore", state: "Tamil Nadu", address: "Beach Road, Cuddalore, Tamil Nadu - 607001", capacityPerDayQuintals: 13000, dailyBookingsCount: 17, activeDockCount: 7, officerInCharge: "Shri M. Anbazhagan", phone: "+91 4142 230 450" },
  { id: "MND-13", name: "Coimbatore MGR Wholesale Market", district: "Coimbatore", state: "Tamil Nadu", address: "Mettupalayam Road, Coimbatore, Tamil Nadu - 641043", capacityPerDayQuintals: 23000, dailyBookingsCount: 39, activeDockCount: 14, officerInCharge: "Shri B. Murugan", phone: "+91 422 244 8899" },
  { id: "MND-14", name: "Kanchipuram Regulated Market Yard", district: "Kanchipuram", state: "Tamil Nadu", address: "Gandhi Road, Kanchipuram, Tamil Nadu - 631501", capacityPerDayQuintals: 12500, dailyBookingsCount: 16, activeDockCount: 6, officerInCharge: "Shri D. Saravanan", phone: "+91 44 2722 3456" },
  { id: "MND-15", name: "Dharmapuri Mango & Grain Market", district: "Dharmapuri", state: "Tamil Nadu", address: "Pennagaram Road, Dharmapuri, Tamil Nadu - 636701", capacityPerDayQuintals: 16500, dailyBookingsCount: 24, activeDockCount: 8, officerInCharge: "Shri P. Ramakrishnan", phone: "+91 4342 260 789" },
  { id: "MND-16", name: "Krishnagiri Vegetable & Fruits Market", district: "Krishnagiri", state: "Tamil Nadu", address: "Rayakottai Road, Krishnagiri, Tamil Nadu - 635001", capacityPerDayQuintals: 17000, dailyBookingsCount: 26, activeDockCount: 9, officerInCharge: "Smt. K. Lalitha", phone: "+91 4343 234 112" },
  { id: "MND-17", name: "Namakkal Poultry & Agricultural Market", district: "Namakkal", state: "Tamil Nadu", address: "Tiruchengode Road, Namakkal, Tamil Nadu - 637001", capacityPerDayQuintals: 15000, dailyBookingsCount: 20, activeDockCount: 8, officerInCharge: "Shri V. Senthilkumar", phone: "+91 4286 222 333" },
  { id: "MND-18", name: "Villupuram Regulated Market Yard", district: "Villupuram", state: "Tamil Nadu", address: "Trichy Main Road, Villupuram, Tamil Nadu - 605602", capacityPerDayQuintals: 14500, dailyBookingsCount: 18, activeDockCount: 7, officerInCharge: "Shri G. Sivakumar", phone: "+91 4146 224 567" },
  { id: "MND-19", name: "Virudhunagar Spices & Grain Market", district: "Virudhunagar", state: "Tamil Nadu", address: "Madurai Road, Virudhunagar, Tamil Nadu - 626001", capacityPerDayQuintals: 16000, dailyBookingsCount: 23, activeDockCount: 8, officerInCharge: "Shri S. Karuppasamy", phone: "+91 4562 243 890" },
  { id: "MND-20", name: "Karur Agricultural Market Yard", district: "Karur", state: "Tamil Nadu", address: "Bypass Road, Karur, Tamil Nadu - 639002", capacityPerDayQuintals: 13500, dailyBookingsCount: 17, activeDockCount: 7, officerInCharge: "Shri R. Dhanapal", phone: "+91 4324 231 678" },
  { id: "MND-21", name: "Dindigul Central Regulated Market", district: "Dindigul", state: "Tamil Nadu", address: "Palani Road, Dindigul, Tamil Nadu - 624001", capacityPerDayQuintals: 15500, dailyBookingsCount: 21, activeDockCount: 8, officerInCharge: "Smt. N. Gomathi", phone: "+91 451 242 3344" },
  { id: "MND-22", name: "Ramanathapuram Chilli & Grain Market", district: "Ramanathapuram", state: "Tamil Nadu", address: "East Car Street, Ramanathapuram, Tamil Nadu - 623501", capacityPerDayQuintals: 14000, dailyBookingsCount: 19, activeDockCount: 7, officerInCharge: "Shri M. Sethuraman", phone: "+91 4567 221 098" },
  { id: "MND-23", name: "Nagercoil Central Market Yard", district: "Kanyakumari", state: "Tamil Nadu", address: "Cape Road, Nagercoil, Tamil Nadu - 629001", capacityPerDayQuintals: 13000, dailyBookingsCount: 16, activeDockCount: 6, officerInCharge: "Shri J. Christopher", phone: "+91 4652 230 765" },
  { id: "MND-24", name: "Tuticorin Port Spices & Grain Yard", district: "Thoothukudi", state: "Tamil Nadu", address: "Palayamkottai Road, Thoothukudi, Tamil Nadu - 628002", capacityPerDayQuintals: 17500, dailyBookingsCount: 25, activeDockCount: 9, officerInCharge: "Shri K. Ponraj", phone: "+91 461 232 4411" },
  { id: "MND-25", name: "Theni Banana & Vegetable Wholesale Hub", district: "Theni", state: "Tamil Nadu", address: "Bypass Road, Theni, Tamil Nadu - 625531", capacityPerDayQuintals: 18000, dailyBookingsCount: 28, activeDockCount: 10, officerInCharge: "Shri T. Veeramani", phone: "+91 4546 252 334" },
  { id: "MND-26", name: "Pudukkottai Regulated Market Yard", district: "Pudukkottai", state: "Tamil Nadu", address: "Tanjore Road, Pudukkottai, Tamil Nadu - 622001", capacityPerDayQuintals: 12000, dailyBookingsCount: 15, activeDockCount: 6, officerInCharge: "Shri R. Vijayakumar", phone: "+91 4322 221 890" },
  { id: "MND-27", name: "Nagapattinam Coastal Paddy Collection Yard", district: "Nagapattinam", state: "Tamil Nadu", address: "Public Office Road, Nagapattinam, Tamil Nadu - 611001", capacityPerDayQuintals: 19500, dailyBookingsCount: 33, activeDockCount: 11, officerInCharge: "Shri S. Natarajan", phone: "+91 4365 224 112" },
  { id: "MND-28", name: "Mayiladuthurai Rice & Grain Market", district: "Mayiladuthurai", state: "Tamil Nadu", address: "Kachery Road, Mayiladuthurai, Tamil Nadu - 609001", capacityPerDayQuintals: 18500, dailyBookingsCount: 30, activeDockCount: 10, officerInCharge: "Shri K. Balasubramanian", phone: "+91 4364 222 556" },
  { id: "MND-29", name: "Kallakurichi Agricultural Market Yard", district: "Kallakurichi", state: "Tamil Nadu", address: "Salem Main Road, Kallakurichi, Tamil Nadu - 606202", capacityPerDayQuintals: 14000, dailyBookingsCount: 18, activeDockCount: 7, officerInCharge: "Shri P. Thangavel", phone: "+91 4151 223 445" },
  { id: "MND-30", name: "Perambalur Regulated Market Yard", district: "Perambalur", state: "Tamil Nadu", address: "Elambalur Road, Perambalur, Tamil Nadu - 621212", capacityPerDayQuintals: 11500, dailyBookingsCount: 14, activeDockCount: 5, officerInCharge: "Shri M. Chinnasamy", phone: "+91 4328 277 890" },
  { id: "MND-46", name: "Tiruvarur Mannargudi Delta Paddy Procurement Hub", district: "Tiruvarur", state: "Tamil Nadu", address: "Bypass Road, Mannargudi, Tiruvarur, TN - 614001", capacityPerDayQuintals: 24000, dailyBookingsCount: 42, activeDockCount: 15, officerInCharge: "Shri S. Tamilselvan", phone: "+91 4367 222 100" },
  { id: "MND-47", name: "Tiruvannamalai Grain & Oilseed Regulated Market", district: "Tiruvannamalai", state: "Tamil Nadu", address: "Polur Road, Tiruvannamalai, TN - 606601", capacityPerDayQuintals: 19000, dailyBookingsCount: 31, activeDockCount: 12, officerInCharge: "Shri K. Annamalai", phone: "+91 4175 233 456" },
  { id: "MND-48", name: "Tenkasi Sankarankovil Agricultural Market", district: "Tenkasi", state: "Tamil Nadu", address: "Rajapalayam Road, Tenkasi, TN - 627811", capacityPerDayQuintals: 16500, dailyBookingsCount: 23, activeDockCount: 9, officerInCharge: "Smt. M. Kanthimathi", phone: "+91 4633 221 567" },
  { id: "MND-49", name: "Sivagangai Karaikudi Regulated Market Yard", district: "Sivagangai", state: "Tamil Nadu", address: "College Road, Karaikudi, Sivagangai, TN - 630002", capacityPerDayQuintals: 14500, dailyBookingsCount: 19, activeDockCount: 8, officerInCharge: "Shri R. Chellappa", phone: "+91 4565 220 890" },
  { id: "MND-50", name: "Ariyalur Cashew & Paddy Collection Centre", district: "Ariyalur", state: "Tamil Nadu", address: "Jayankondam Road, Ariyalur, TN - 621704", capacityPerDayQuintals: 15000, dailyBookingsCount: 20, activeDockCount: 8, officerInCharge: "Shri T. Rajavelu", phone: "+91 4329 223 344" },
  { id: "MND-51", name: "Tiruvallur Red Hills Grain Wholesale Market", district: "Tiruvallur", state: "Tamil Nadu", address: "GNT Road, Red Hills, Tiruvallur, TN - 600052", capacityPerDayQuintals: 21000, dailyBookingsCount: 36, activeDockCount: 13, officerInCharge: "Shri V. Parthiban", phone: "+91 44 2631 8899" },
  { id: "MND-52", name: "Chengalpattu Maduranthakam DPC Centre", district: "Chengalpattu", state: "Tamil Nadu", address: "GST Road, Maduranthakam, Chengalpattu, TN - 603306", capacityPerDayQuintals: 16000, dailyBookingsCount: 22, activeDockCount: 9, officerInCharge: "Shri G. Kumaresan", phone: "+91 44 2755 1234" },
  { id: "MND-53", name: "Nilgiris Ooty Vegetable & Tea Collection Hub", district: "The Nilgiris", state: "Tamil Nadu", address: "Commercial Road, Ooty, Nilgiris, TN - 643001", capacityPerDayQuintals: 13500, dailyBookingsCount: 17, activeDockCount: 7, officerInCharge: "Shri H. Bellan", phone: "+91 423 244 5678" },
  { id: "MND-54", name: "Ranipet Arcot Agricultural Regulated Yard", district: "Ranipet", state: "Tamil Nadu", address: "Bypass Road, Arcot, Ranipet, TN - 632503", capacityPerDayQuintals: 15500, dailyBookingsCount: 21, activeDockCount: 8, officerInCharge: "Shri N. Sampath", phone: "+91 4172 225 678" },
  { id: "MND-55", name: "Tirupattur Vaniyambadi Produce Market", district: "Tirupattur", state: "Tamil Nadu", address: "CL Road, Vaniyambadi, Tirupattur, TN - 635751", capacityPerDayQuintals: 14000, dailyBookingsCount: 18, activeDockCount: 7, officerInCharge: "Shri M. Venkatesan", phone: "+91 4174 232 112" },
  { id: "MND-56", name: "Kanyakumari Marthandam Honey & Spices Hub", district: "Kanyakumari", state: "Tamil Nadu", address: "Main Road, Marthandam, Kanyakumari, TN - 629165", capacityPerDayQuintals: 12500, dailyBookingsCount: 15, activeDockCount: 6, officerInCharge: "Shri P. Mohan", phone: "+91 4651 270 345" },
  { id: "MND-57", name: "Erode Perundurai Turmeric Marketing Complex", district: "Erode", state: "Tamil Nadu", address: "SIPCOT Industrial Complex, Perundurai, TN - 638052", capacityPerDayQuintals: 25000, dailyBookingsCount: 45, activeDockCount: 16, officerInCharge: "Shri A. Sengottaiyan", phone: "+91 4294 220 900" },
  { id: "MND-58", name: "Salem Attur Tapioca & Sago Wholesale Market", district: "Salem", state: "Tamil Nadu", address: "Cuddalore Main Road, Attur, Salem, TN - 636102", capacityPerDayQuintals: 22000, dailyBookingsCount: 38, activeDockCount: 14, officerInCharge: "Shri C. Palanisamy", phone: "+91 4282 240 123" },
  { id: "MND-59", name: "Thanjavur Orathanadu Direct Paddy Procurement Centre", district: "Thanjavur", state: "Tamil Nadu", address: "Pattukkottai Road, Orathanadu, Thanjavur, TN - 614625", capacityPerDayQuintals: 23000, dailyBookingsCount: 40, activeDockCount: 14, officerInCharge: "Shri S. Vaithilingam", phone: "+91 4372 233 890" },
  { id: "MND-60", name: "Coimbatore Mettupalayam Vegetable Wholesale Market", district: "Coimbatore", state: "Tamil Nadu", address: "Ooty Road, Mettupalayam, Coimbatore, TN - 641301", capacityPerDayQuintals: 20000, dailyBookingsCount: 34, activeDockCount: 12, officerInCharge: "Shri R. Velumani", phone: "+91 4254 222 345" }
];

const STOCKYARD_FACILITIES = [
  {
    id: "STK-01",
    name: "Uzhavar Climate Grain Silos & Warehouse",
    location: "Koyambedu, Chennai (TN)",
    capacityMT: 15000,
    occupiedMT: 8400,
    dailyRatePerMT: 25,
    tempCelsius: 21.5,
    humidityPercent: 48,
    supportedCrops: ["PADDY_PONNI", "PADDY_SEERAGA_SAMBA", "WHEAT", "SUGARCANE"]
  },
  {
    id: "STK-02",
    name: "Madurai Mega Cold Storage Hub",
    location: "Mattuthavani, Madurai (TN)",
    capacityMT: 12000,
    occupiedMT: 7100,
    dailyRatePerMT: 30,
    tempCelsius: 18.0,
    humidityPercent: 52,
    supportedCrops: ["TOMATO", "SHALLOTS_ONION", "MANGO_ALPHONSO", "BANANA_NENDRAN"]
  },
  {
    id: "STK-03",
    name: "Erode Spices & Turmeric Dry Stockyard",
    location: "Karur Bypass, Erode (TN)",
    capacityMT: 10000,
    occupiedMT: 4500,
    dailyRatePerMT: 28,
    tempCelsius: 24.0,
    humidityPercent: 42,
    supportedCrops: ["TURMERIC", "RED_CHILLI"]
  }
];

const VEHICLE_TYPES = [
  { id: "TRACTOR_TROLLEY", name: "Tractor Trolley", capacityQuintals: 80, slotMultiplier: 1 },
  { id: "MINI_TRUCK", name: "Mini Truck (Pickup / Commercial)", capacityQuintals: 30, slotMultiplier: 0.5 },
  { id: "HEAVY_TRUCK", name: "Heavy Commercial Truck (10-Wheeler)", capacityQuintals: 200, slotMultiplier: 2 },
  { id: "BULLOCK_CART", name: "Bullock Cart / Manual Cart", capacityQuintals: 15, slotMultiplier: 0.3 }
];

const INITIAL_FARMER_PROFILE = {
  id: "FAR-2026-8812",
  name: "Ramesh Singh Kumar",
  aadhaar: "XXXX-XXXX-4921",
  mobile: "+91 98765 43210",
  village: "Koyambedu / Madurai",
  district: "Madurai",
  state: "Tamil Nadu",
  landAcres: 8.5,
  bankName: "State Bank of India",
  accountNo: "••••••••6719",
  ifsc: "SBIN0001234",
  ekycStatus: "VERIFIED",
  verifiedDate: "2026-08-25"
};

const INITIAL_TOKENS = [
  {
    tokenNo: 101,
    farmerId: "FAR-2026-8812",
    farmerName: "Ramesh Singh Kumar",
    mandiId: "MND-01",
    mandiName: "Koyambedu Wholesale Market Complex",
    cropId: "PADDY_PONNI",
    cropName: "Ponni Paddy / Rice (Grade A)",
    quantityInput: 65,
    unit: "QUINTAL",
    quantityKg: 6500,
    quantityMT: 6.5,
    vehicleType: "TRACTOR_TROLLEY",
    vehicleRegNo: "TN-57-AB-4921",
    bookingDate: "2026-08-28",
    timeSlot: "09:00 AM - 10:00 AM",
    status: "QUALITY_CHECK",
    gateEntryTime: "08:45 AM",
    moisturePercent: 12.8,
    qualityGrade: "Grade A Approved",
    assignedScaleDock: "Scale Dock #2",
    weightGrossKg: 7850,
    weightTareKg: 1350,
    weightNetKg: 6500,
    totalPaymentAmount: 149500,
    paymentTxnId: "TXN-SBI-20260828-99412",
    qrCodeText: "TOKEN:101|FAR:FAR-2026-8812|MND:MND-01|DATE:2026-08-28"
  }
];

const INITIAL_STOCKYARD_BOOKINGS = [
  {
    id: "SYB-901",
    facilityId: "STK-01",
    facilityName: "Uzhavar Climate Grain Silos & Warehouse",
    farmerId: "FAR-2026-8812",
    farmerName: "Ramesh Singh Kumar",
    cropId: "WHEAT",
    cropName: "Sharbati Wheat (Grade A)",
    quantityMT: 15,
    quantityKg: 15000,
    durationDays: 30,
    dailyRatePerMT: 25,
    totalFee: 11250,
    startDate: "2026-08-20",
    endDate: "2026-09-19",
    status: "STORED",
    assignedBay: "Silo Bay B-04",
    receiptQrText: "STK:STK-01|BAY:B-04|MT:15|FAR:FAR-2026-8812",
    lastInspectedTemp: 21.5,
    lastInspectedHumidity: 48
  }
];

const VEHICLE_NAMES_I18N = {
  TRACTOR_TROLLEY: { en: "Tractor Trolley", ta: "டிராக்டர் டிராலி", hi: "ट्रैक्टर ट्रॉली", te: "ట్రాక్టర్ ట్రాలీ", ml: "ട്രാക്ടർ ട്രോളി", kn: "ಟ್ರ್ಯಾಕ್ಟರ್ ಟ್ರಾಲಿ" },
  MINI_TRUCK: { en: "Mini Truck (Pickup)", ta: "மினி டிரக் (பிக்கப்)", hi: "मिनी ट्रक (पिकअप)", te: "మిని ట్రక్", ml: "മിനി ട്രക്ക്", kn: "ಮಿನಿ ಟ್ರಕ್" },
  HEAVY_TRUCK: { en: "Heavy Commercial Truck (10-Wheeler)", ta: "கனரக டிரக் (10-சக்கரம்)", hi: "भारी ट्रक (10-व्हीलर)", te: "హెవీ ట్రక్", ml: "ഹെവി ട്രക്ക്", kn: "ಹೆವಿ ಟ್ರಕ್" },
  BULLOCK_CART: { en: "Bullock Cart / Manual Cart", ta: "மாட்டு வண்டி / கைவண்டி", hi: "बैलगाड़ी / हाथगाड़ी", te: "ఎడ్ల బండి", ml: "കാളവണ്ടി", kn: "ಎತ್ತಿನ ಬಂಡಿ" }
};

const STATUS_NAMES_I18N = {
  GATE_ENTRY: { en: "Gate Entry Confirmed", ta: "கேட் நுழைவு உறுதி செய்யப்பட்டது", hi: "गेट प्रवेश की पुष्टि", te: "గేట్ నమోదు నిర్ధారించబడింది", ml: "ഗേറ്റ് പ്രവേശനം ഉറപ്പാക്കി", kn: "ಗೇಟ್ ಪ್ರವೇಶ ಖಚಿತಪಟ್ಟಿದೆ" },
  QUALITY_CHECK: { en: "Moisture & Quality Inspection Passed", ta: "ஈரப்பதம் & தர பரிசோதனை முடிந்தது", hi: "नमी व गुणवत्ता जांच उत्तीर्ण", te: "నాణ్యత తనిఖీ పూర్తయింది", ml: "ഗുണനിലവാര പരിശോധന പൂർത്തിയായി", kn: "ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಂಡಿದೆ" },
  WEIGHBRIDGE: { en: "Weighbridge Scale Logged", ta: "எடை மேடை பதிவு செய்யப்பட்டது", hi: "वेब्रिज कांटे में वजन दर्ज", te: "తూకం నమోదు చేయబడింది", ml: "തൂക്ക വിവരങ്ങൾ രേഖപ്പെടുത്തി", kn: "ತೂಕದ ಯಂತ್ರದಲ್ಲಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ" },
  UNLOADING: { en: "Unloading at Market Dock", ta: "சரக்கு இறக்கும் மேடை", hi: "मंडी डॉक पर उतराई जारी", te: "సరుకు దింపుతున్నారు", ml: "ചരക്ക് ഇറക്കുന്നു", kn: "ಸರಕು ಇಳಿಸಲಾಗುತ್ತಿದೆ" },
  PAYMENT_DONE: { en: "Direct Bank Payment Sent", ta: "வங்கி கணக்கில் பணம் செலுத்தப்பட்டது", hi: "सीधे बैंक खाते में भुगतान सफल", te: "బ్యాంక్ ఖాతాలో డబ్బు జమ చేయబడింది", ml: "ബാങ്ക് പേയ്‌മെന്റ് പൂർത്തിയായി", kn: "ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಹಣ ಪಾವತಿಯಾಗಿದೆ" },
  STORED: { en: "Climate Storage Active", ta: "தானியக் கிடங்கில் சேமிக்கப்பட்டது", hi: "गोदाम में सुरक्षित जमा", te: "గోదాములో నిల్వ చేయబడింది", ml: "ഗോഡൗണിൽ സൂക്ഷിച്ചിരിക്കുന്നു", kn: "ಗೋದಾಮಿನಲ್ಲಿ ಶೇಖರಿಸಲಾಗಿದೆ" }
};

const CATEGORY_NAMES_I18N = {
  "Cereals": { en: "Cereals", ta: "தானியங்கள்", hi: "अनाज", te: "ధాన్యాలు", ml: "ധാന്യങ്ങൾ", kn: "ಧಾನ್ಯಗಳು" },
  "Pulses": { en: "Pulses", ta: "பருப்பு வகைகள்", hi: "दालें", te: "పప్పుధాన్యాలు", ml: "പയറുവർഗ്ഗങ്ങൾ", kn: "ಬೇಳೆಕಾಳುಗಳು" },
  "Oilseeds": { en: "Oilseeds", ta: "எண்ணெய் வித்துக்கள்", hi: "तिलहन", te: "నూనెగింజలు", ml: "എണ്ണക്കുരുക്കൾ", kn: "ಎಣ್ಣೆಕಾಳುಗಳು" },
  "Spices": { en: "Spices", ta: "மசாலா பொருட்கள்", hi: "मसाले", te: "సుగంధ ద్రవ్యాలు", ml: "സുഗന്ധവ്യഞ്ജനനങ്ങൾ", kn: "ಮಸಾಲೆ ಪದಾರ್ಥಗಳು" },
  "Fruits & Vegetables": { en: "Fruits & Vegetables", ta: "காய்கறிகள் & பழங்கள்", hi: "फल एवं सब्जियां", te: "కూరగాయలు & పండ్లు", ml: "പച്ചക്കറികളും പഴങ്ങളും", kn: "ತರಕಾರಿ ಮತ್ತು ಹಣ್ಣುಗಳು" },
  "Cash Crops": { en: "Cash Crops", ta: "பணப் பயிர்கள்", hi: "नकदी फसलें", te: "వాణిజ్య పంటలు", ml: "നാണ്യവിളകൾ", kn: "ವಾಣಿಜ್ಯ ಬೆಳೆಗಳು" }
};

const I18N = {
  en: {
    appTitle: "Uzhavar Mutram",
    tagline: "Direct Tamil Nadu Crop Selling, Storage Rental & Smart Queue System",
    farmerPortal: "Farmer Portal",
    officerPortal: "Market Officer Admin",
    buyerPortal: "Wholesale Buyer",
    kioskPortal: "Display Board",
    switchAccount: "Login / Switch Account",
    audioHelper: "🔊 Audio Voice Helper",
    voiceCommandEngine: "🎙️ Voice Command Engine",
    bookSlot: "Book Selling Slot",
    queueTracker: "Live Line Tracker",
    marketPrices: "📈 Live Prices & Trends",
    stockyard: "🏭 Stockyard Storage Rental",
    myPasses: "My Passes & Receipts",
    mspRates: "Govt Crop Prices (MSP)",
    profile: "My Bank & Aadhaar eKYC",
    customerCare: "📞 Customer Support & Helpline",
    bookSlotTitle: "Book Crop Selling Slot",
    govtVerifiedPortal: "Govt Verified Portal",
    selectMandi: "Select Market / Collection Centre",
    selectCrop: "Select Crop Type",
    quantityUnit: "Quantity & Unit Input",
    unitQuintals: "Quintals (100kg)",
    unitMT: "Metric Tons (MT)",
    unitBags: "Bags (50kg)",
    unitKg: "Kilograms (Kg)",
    vehicleType: "Transport Vehicle",
    vehicleNo: "Vehicle Reg. Number",
    selectDate: "Crop Delivery Date",
    selectTimeSlot: "Select Time Slot",
    slotCapacity: "Market Line & Wait Level",
    confirmBooking: "🎟️ Confirm Slot & Get QR Token",
    benefitsTitle: "Benefits of Direct Online Booking",
    noLongLinesTitle: "No Long Lines:",
    noLongLinesText: "Arrive at your booked hour; skip 8+ hours waiting in tractor queues.",
    guaranteedGovtRateTitle: "Guaranteed Govt Rate:",
    guaranteedGovtRateText: "Sell directly at full Minimum Support Price (MSP) with no middleman commission.",
    standardizedWeightingTitle: "Standardized Weighting:",
    standardizedWeightingText: "All crop weights converted & verified in Kilograms (Kg) and Metric Tons (MT).",
    directBankTransferTitle: "Direct Bank Transfer:",
    directBankTransferText: "Money sent directly into your registered bank account within 24 to 48 hours.",
    sellerNameLabel: "Farmer / Seller Full Name",
    sellerNamePlaceholder: "Enter your full name (e.g. Ramesh Kumar)",
    welcomeModalTitle: "Welcome to Uzhavar Mutram Portal",
    welcomeModalSubtitle: "Tamil Nadu Smart Agricultural Marketplace System",
    enterGuestBtn: "🌱 Enter Without Login (Guest Mode)",
    loginRegisterBtn: "🔑 Login / Register Account",
    guestNotice: "In Guest Mode, you can freely browse live market rates, check storage facilities, and book crop selling slots.",
    offlineMode: "⚡ Offline Mode: Accessing Cached Uzhavar Mutram Data & Booked Passes",
    mobileSmsAlertsTitle: "Mobile SMS Alerts",
    sendBtn: "Send",
    chatPlaceholder: "Ask me to book a slot, check prices, or find storage...",
    catAll: "All Crops",
    catCereals: "Cereals",
    catPulses: "Pulses",
    catOilseeds: "Oilseeds",
    catSpices: "Spices",
    catVegetables: "Vegetables & Fruits",
    catCashCrops: "Cash Crops",
    gateEntry: "Gate Entry Confirmed",
    qualityTesting: "Moisture & Quality Inspection Passed",
    weightScales: "Weighbridge Scale Logged",
    paymentsSent: "Direct Bank Payment Sent",
    searchMarketPlaceholder: "Search crop name, category, or district market...",
    welcomeText: "Welcome to Uzhavar Mutram. You can book crop selling slots, check live market prices, rent climate-controlled stockyard storage, and track your queue token in real time.",
    activeAuctions: "Active Auctions",
    myBids: "My Bids",
    escrowBalance: "Escrow Balance",
    stockyardContracts: "Stockyard Contracts"
  },
  ta: {
    appTitle: "உழவர் முற்றம் (Uzhavar Mutram)",
    tagline: "தமிழ்நாடு வேளாண் விற்பனை மண்டலம் & ஸ்மார்ட் வரிசை முறை",
    farmerPortal: "விவசாயி போர்டல்",
    officerPortal: "சந்தை அதிகாரி நிர்வாகம்",
    buyerPortal: "மொத்த கொள்முதல் வணிகர்",
    kioskPortal: "சந்தை நேரடி திரை",
    switchAccount: "உள்நுழை / கணக்கு மாற்று",
    audioHelper: "🔊 ஒலி உதவி",
    voiceCommandEngine: "🎙️ குரல் கட்டளை கருவி",
    bookSlot: "விற்பனை ஸ்லாட் பதிவு",
    queueTracker: "நேரடி வரிசை கண்காணிப்பு",
    marketPrices: "📈 சந்தை விலைகள் & போக்கு",
    stockyard: "🏭 தானிய கிடங்கு சேமிப்பு",
    myPasses: "எனது அனுமதி சீட்டுகள்",
    mspRates: "அரசு குறைந்தபட்ச ஆதரவு விலை (MSP)",
    profile: "வங்கி கணக்கு & Aadhaar eKYC",
    customerCare: "📞 வாடிக்கையாளர் உதவி மையம்",
    bookSlotTitle: "பயிர் விற்பனை ஸ்லாட் பதிவு செய்க",
    govtVerifiedPortal: "தமிழ்நாடு அரசு அங்கீகரிக்கப்பட்ட தளம்",
    selectMandi: "சந்தை / நேரடி கொள்முதல் நிலையத்தை தேர்ந்தெடுக்கவும்",
    selectCrop: "விற்பனை பயிர் வகையை தேர்ந்தெடுக்கவும்",
    quantityUnit: "அளவு & அலகு உள்ளீடு",
    unitQuintals: "குவிண்டால் (100 கிலோ)",
    unitMT: "மெட்ரிக் டன் (MT)",
    unitBags: "மூட்டைகள் (50 கிலோ)",
    unitKg: "கிலோகிராம் (Kg)",
    vehicleType: "போக்குவரத்து வாகனம்",
    vehicleNo: "வாகன பதிவு எண்",
    selectDate: "சந்தைக்கு வரும் தேதி",
    selectTimeSlot: "நேர ஸ்லாட் தேர்ந்தெடுக்கவும்",
    slotCapacity: "சந்தை வரிசை & காத்திருப்பு நிலை",
    confirmBooking: "🎟️ ஸ்லாட் உறுதி செய்து QR சீட்டு பெறுக",
    benefitsTitle: "⚡ ஆன்லைன் முன்பதிவின் நன்மைகள்",
    noLongLinesTitle: "நீண்ட வரிசை இல்லை:",
    noLongLinesText: "குறிப்பிட்ட நேரத்தில் வரலாம்; டிராக்டர் வரிசையில் பல மணி நேரம் காத்திருக்க வேண்டியதில்லை.",
    guaranteedGovtRateTitle: "உறுதிசெய்யப்பட்ட அரசு விலை:",
    guaranteedGovtRateText: "இடைத்தரகர் கமிஷன் இல்லாமல் முழு ஆதரவு விலைக்கு விற்கலாம்.",
    standardizedWeightingTitle: "துல்லியமான எடை அளவீடு:",
    standardizedWeightingText: "அனைத்து எடைகளும் டிஜிட்டல் எடை மேடையில் துல்லியமாக கணக்கிடப்படும்.",
    directBankTransferTitle: "நேரடி வங்கி பரிமாற்றம்:",
    directBankTransferText: "24 முதல் 48 மணி நேரத்திற்குள் பணம் நேரடியாக உங்களது வங்கி கணக்கில் சேரும்.",
    sellerNameLabel: "விவசாயி / விற்பனையாளர் பெயர்",
    sellerNamePlaceholder: "உங்களது முழு பெயரை பதிவு செய்யவும் (எ.கா. ரமேஷ் குமார்)",
    welcomeModalTitle: "உழவர் முற்றம் வாயிலுக்கு வரவேற்கிறோம்",
    welcomeModalSubtitle: "தமிழ்நாடு ஸ்மார்ட் வேளாண் சந்தை போர்டல்",
    enterGuestBtn: "🌱 உள்நுழையாமல் தொடரவும் (விருந்தினர் நிலை)",
    loginRegisterBtn: "🔑 கணக்கில் உள்நுழைய / பதிவு செய்ய",
    guestNotice: "விருந்தினர் நிலையில் சந்தை விலைகள், தானிய கிடங்கு மற்றும் விற்பனை ஸ்லாட்டுகளை உடனடியாக பார்வையிடலாம்.",
    offlineMode: "⚡ ஆஃப்லைன் நிலை: சேமிக்கப்பட்ட உழவர் முற்றம் தரவு",
    mobileSmsAlertsTitle: "எஸ்.எம்.எஸ் எச்சரிக்கை அறிவிப்பு",
    sendBtn: "அனுப்பு",
    chatPlaceholder: "ஸ்லாட் பதிவு செய்ய, சந்தை விலை அறிய அல்லது கிடங்கு பற்றி கேட்கவும்...",
    catAll: "அனைத்து பயிர்களும்",
    catCereals: "தானியங்கள்",
    catPulses: "பருப்பு வகைகள்",
    catOilseeds: "எண்ணெய் வித்துக்கள்",
    catSpices: "மசாலா பொருட்கள்",
    catVegetables: "காய்கறிகள் & பழங்கள்",
    catCashCrops: "பணப் பயிர்கள்",
    gateEntry: "கேட் நுழைவு உறுதி செய்யப்பட்டது",
    qualityTesting: "ஈரப்பதம் & தர பரிசோதனை முடிந்தது",
    weightScales: "எடை மேடை பதிவு செய்யப்பட்டது",
    paymentsSent: "வங்கி கணக்கில் பணம் செலுத்தப்பட்டது",
    searchMarketPlaceholder: "பயிர் பெயர் அல்லது மாவட்ட சந்தையை தேடுக...",
    welcomeText: "உழவர் முற்றத்திற்கு வரவேற்கிறோம். விற்பனை ஸ்லாட் பதிவு, நேரலை சந்தை விலைகள், கிடங்கு வாட்கை மற்றும் வரிசை டோக்கன் கண்காணிப்பு ஆகியவை செய்யலாம்.",
    activeAuctions: "நடைமுறை ஏலங்கள்",
    myBids: "எனது ஏலவிலைகள்",
    escrowBalance: "பணப்பாதுகாப்பு இருப்பு",
    stockyardContracts: "கிடங்கு ஒப்பந்தங்கள்"
  },
  hi: {
    appTitle: "उझावर मुत्रम (Uzhavar Mutram)",
    tagline: "तमिलनाडु फसल बिक्री, भंडारण और स्मार्ट कतार प्रणाली",
    farmerPortal: "किसान पोर्टल",
    officerPortal: "मंडी अधिकारी प्रशासन",
    buyerPortal: "थोक खरीदार",
    kioskPortal: "प्रदर्शन बोर्ड",
    switchAccount: "लॉगिन / खाता बदलें",
    audioHelper: "🔊 ऑडियो आवाज सहायता",
    voiceCommandEngine: "🎙️ वॉइस कमांड इंजन",
    bookSlot: "बिक्री स्लॉट बुक करें",
    queueTracker: "लाइव कतार ट्रैकर",
    marketPrices: "📈 लाइव दरें व रुझान",
    stockyard: "🏭 गोदाम भंडारण किराया",
    myPasses: "मेरे पास और रसीदें",
    mspRates: "सरकारी समर्थन मूल्य (MSP)",
    profile: "मेरा बैंक व आधार eKYC",
    customerCare: "📞 ग्राहक सेवा व हेल्पलाइन",
    bookSlotTitle: "फसल बिक्री स्लॉट बुक करें",
    govtVerifiedPortal: "सरकारी सत्यापित पोर्टल",
    selectMandi: "मंडी / संग्रह केंद्र चुनें",
    selectCrop: "फसल का प्रकार चुनें",
    quantityUnit: "मात्रा और इकाई इनपुट",
    unitQuintals: "क्विंटल (100 किग्रा)",
    unitMT: "मीट्रिक टन (MT)",
    unitBags: "बोरी (50 किग्रा)",
    unitKg: "किलोग्राम (Kg)",
    vehicleType: "परिवहन वाहन",
    vehicleNo: "वाहन पंजीकरण संख्या",
    selectDate: "फसल वितरण तिथि",
    selectTimeSlot: "समय स्लॉट चुनें",
    slotCapacity: "मंडी भीड़ स्तर",
    confirmBooking: "🎟️ स्लॉट बुक करें और QR टोकन पाएं",
    benefitsTitle: "⚡ ऑनलाइन बुकिंग के लाभ",
    noLongLinesTitle: "लंबी कतारों से मुक्ति:",
    noLongLinesText: "निर्धारित समय पर आएं; घंटों लाइन में इंतजार करने की जरूरत नहीं।",
    guaranteedGovtRateTitle: "गारंटीकृत सरकारी दर:",
    guaranteedGovtRateText: "बिना बिचौलियों के सीधे पूरा MSP मूल्य प्राप्त करें।",
    standardizedWeightingTitle: "मानकीकृत वजन:",
    standardizedWeightingText: "सभी फसलों का वजन किलोग्राम और मीट्रिक टन में पारदर्शी रूप से दर्ज होता है।",
    directBankTransferTitle: "सीधा बैंक ट्रांसफर:",
    directBankTransferText: "24 से 48 घंटों में आपके पंजीकृत बैंक खाते में सीधे भुगतान।",
    sellerNameLabel: "किसान / विक्रेता का नाम",
    sellerNamePlaceholder: "अपना पूरा नाम दर्ज करें (जैसे रमेश सिंह)",
    welcomeModalTitle: "उझावर मुत्रम में आपका स्वागत है",
    welcomeModalSubtitle: "तमिलनाडु स्मार्ट कृषि मंडी प्रणाली",
    enterGuestBtn: "🌱 बिना लॉगिन प्रवेश करें (गेस्ट मोड)",
    loginRegisterBtn: "🔑 खाते में लॉगिन करें / पंजीकरण करें",
    guestNotice: "गेस्ट मोड में आप लाइव दरें, गोदाम स्थान और स्लॉट आसानी से देख सकते हैं।",
    offlineMode: "⚡ ऑफ़लाइन मोड: सहेजा गया डेटा",
    mobileSmsAlertsTitle: "एसएमएस अलर्ट सिम्युलेटर",
    sendBtn: "भेजें",
    chatPlaceholder: "स्लॉट बुक करने, कीमतें या गोदाम जानने के लिए पूछें...",
    catAll: "सभी फसलें",
    catCereals: "अनाज",
    catPulses: "दालें",
    catOilseeds: "तिलहन",
    catSpices: "मसाले",
    catVegetables: "फल व सब्जियां",
    catCashCrops: "नकदी फसलें",
    gateEntry: "गेट प्रवेश की पुष्टि",
    qualityTesting: "गुणवत्ता व नमी जांच सफल",
    weightScales: "वेब्रिज कांटा वजन दर्ज",
    paymentsSent: "सीधे बैंक खाते में भुगतान सफल",
    searchMarketPlaceholder: "फसल का नाम या मंडी खोजें...",
    welcomeText: "उझावर मुत्रम में आपका स्वागत है। आप फसल बिक्री स्लॉट बुक कर सकते हैं, लाइव मंडी भाव देख सकते हैं, गोदाम भंडारण किराया ले सकते हैं और अपना क्यू टोकन ट्रैक कर सकते हैं।",
    activeAuctions: "सक्रिय नीलामी",
    myBids: "मेरी बोलियां",
    escrowBalance: "एस्क्रो शेष",
    stockyardContracts: "गोदाम अनुबंध"
  },
  te: {
    appTitle: "ఉళవర్ ముట్రమ్ (Uzhavar Mutram)",
    tagline: "తమిళనాడు పంట విక్రయాలు, నిల్వ & స్మార్ట్ క్యూ వ్యవస్థ",
    farmerPortal: "రైతు పోర్టల్",
    officerPortal: "మార్కెట్ అధికారి అడ్మిన్",
    buyerPortal: "హోల్‌సేల్ కొనుగోలుదారు",
    kioskPortal: "ప్రదర్శన బోర్డు",
    switchAccount: "లాగిన్ / ఖాతా మార్చండి",
    audioHelper: "🔊 ఆడియో సహాయం",
    voiceCommandEngine: "🎙️ వాయిస్ కమాండ్ ఇంజిన్",
    bookSlot: "అమ్మకం స్లాట్ బుక్ చేయండి",
    queueTracker: "లైవ్ లైన్ ట్రాకర్",
    marketPrices: "📈 లైవ్ ధరలు & ట్రెండ్స్",
    stockyard: "🏭 కోల్డ్ స్టోరేజ్ అద్దె",
    myPasses: "నా పాస్‌లు & రసీదులు",
    mspRates: "ప్రభుత్వ మద్దతు ధర (MSP)",
    profile: "నా బ్యాంకు & Aadhaar eKYC",
    customerCare: "📞 కస్టమర్ సపోర్ట్",
    bookSlotTitle: "పంట అమ్మకం స్లాట్ బుక్ చేయండి",
    govtVerifiedPortal: "ప్రభుత్వ ధృవీకరించిన పోర్టల్",
    selectMandi: "మార్కెట్ / సేకరణ కేంద్రం ఎంచుకోండి",
    selectCrop: "పంట రకం ఎంచుకోండి",
    quantityUnit: "పరిమాణం & యూనిట్",
    unitQuintals: "క్వింటాళ్ళు (100kg)",
    unitMT: "మెట్రిక్ టన్నులు (MT)",
    unitBags: "బస్తాలు (50kg)",
    unitKg: "కిలోగ్రాములు (Kg)",
    vehicleType: "రవాణా వాహనం",
    vehicleNo: "వాహనం నంబర్",
    selectDate: "పంపిణీ తేదీ",
    selectTimeSlot: "సమయం స్లాట్",
    slotCapacity: "రద్దీ స్థాయి",
    confirmBooking: "🎟️ స్లాట్ నిర్ధారించి QR టోకెన్ పొందండి",
    benefitsTitle: "⚡ ఆన్‌లైన్ బుకింగ్ ప్రయోజనాలు",
    noLongLinesTitle: "లైన్ల వేచియుండాల్సిన అవసరం లేదు",
    noLongLinesText: "మీరు ఎంచుకున్న సమయానికి చేరుకోండి; గంటల తరబడి వేచి ఉండక్కర్లేదు.",
    guaranteedGovtRateTitle: "హామీ ఇచ్చే ప్రభుత్వ మద్దతు ధర",
    guaranteedGovtRateText: "దళారుల కమీషన్ లేకుండా నేరుగా అమ్మండి.",
    standardizedWeightingTitle: "పారదర్శక తూకం",
    standardizedWeightingText: "డిజిటల్ పరికరాల ద్వారా కిలోలు మరియు టన్నులలో కచ్చితమైన తూకం.",
    directBankTransferTitle: "నేరుగా బ్యాంకు బదిలీ",
    directBankTransferText: "24-48 గంటల్లో డబ్బు నేరుగా మీ ఖాతాలో పడుతుంది.",
    sellerNameLabel: "రైతు / విక్రేత పూర్తి పేరు",
    sellerNamePlaceholder: "మీ పేరు నమోదు చేయండి (ఉదా: రమేష్ కుమార్)",
    welcomeModalTitle: "ఉళవర్ ముట్రమ్‌కి స్వాగతం",
    welcomeModalSubtitle: "తమిళనాడు స్మార్ట్ అగ్రికల్చర్ పోర్టల్",
    enterGuestBtn: "🌱 లాగిన్ లేకుండా కొనసాగండి (గెస్ట్ మోడ్)",
    loginRegisterBtn: "🔑 ఖాతా లాగిన్ / నమోదు",
    guestNotice: "గెస్ట్ మోడ్‌లో మీరు మార్కెట్ ధరలు, నిల్వ వివరాలు మరియు స్లాట్ బుకింగ్ చేయవచ్చు.",
    offlineMode: "⚡ ఆఫ్‌లైన్ మోడ్",
    mobileSmsAlertsTitle: "SMS అలర్ట్",
    sendBtn: "పంపండి",
    chatPlaceholder: "స్లాట్ బుకింగ్, ధరల కోసం అడగండి...",
    catAll: "అన్ని పంటలు",
    catCereals: "ధాన్యాలు",
    catPulses: "పప్పు ధాన్యాలు",
    catOilseeds: "నూనె గింజలు",
    catSpices: "సుగంధ ద్రవ్యాలు",
    catVegetables: "కూరగాయలు & పండ్లు",
    catCashCrops: "వాణిజ్య పంటలు",
    gateEntry: "గేట్ ప్రవేశం ఖాయమైంది",
    qualityTesting: "నాణ్యత తనిఖీ పూర్తయింది",
    weightScales: "తూకం నమోదైంది",
    paymentsSent: "ఖాతాలో డబ్బు జమ అయింది",
    searchMarketPlaceholder: "పంట లేదా మార్కెట్ వెతకండి...",
    welcomeText: "ఉజవర్ ముత్రంకు స్వాగతం. పంట అమ్కాడిక స్లాట్ బుక్ చల్లవచ్చు, ప్రత్యక్ష మార్కెట్ ధరలు చూడవచ్చు, గోదాము నిల్వ అద్దించవచ్చు, క్యూ టోకెన్ ట్రాక్ చేయవచ్చు.",
    activeAuctions: "క్రియావ్‌లో వేలములు",
    myBids: "నా బిడ్స్",
    escrowBalance: "ఎస్క్రో బాకీ",
    stockyardContracts: "గోదాము కంట్రాక్ట్స్"
  },
  ml: {
    appTitle: "ഉഴവർ മുറ്റം (Uzhavar Mutram)",
    tagline: "തമിഴ്‌നാട് കാർഷിക വിപണനവും സ്മാർട്ട് ക്യൂ സിസ്റ്റവും",
    farmerPortal: "കർഷക പോർട്ടൽ",
    officerPortal: "മാർക്കറ്റ് ഓഫീസ് അഡ്മിൻ",
    buyerPortal: "ഹോൾസെയിൽ ബയർ",
    kioskPortal: "ലൈവ് ഡിസ്പ്ലേ ബോർഡ്",
    switchAccount: "ലോഗിൻ / അക്കൗണ്ട് മാറ്റുക",
    audioHelper: "🔊 വോയ്‌സ് ഹെൽപ്പ്",
    voiceCommandEngine: "🎙️ വോയ്‌സ് കമാൻഡ് എൻജിൻ",
    bookSlot: "വിൽപ്പന സ്ലോട്ട് ബുക്ക് ചെയ്യുക",
    queueTracker: "ക്യൂ ട്രാക്കിംഗ്",
    marketPrices: "📈 മാർക്കറ്റ് നിരക്കുകൾ",
    stockyard: "🏭 സംഭരണ ശാല വാടകക്ക്",
    myPasses: "എന്റെ പാസ്സുകൾ & റെസിപ്റ്റുകൾ",
    mspRates: "തറവില വിവരങ്ങൾ (MSP)",
    profile: "ബാങ്ക് വിവരങ്ങൾ & eKYC",
    customerCare: "📞 കസ്റ്റമർ സപ്പോർട്ട്",
    bookSlotTitle: "വിൽപ്പന സ്ലോട്ട് ബുക്ക് ചെയ്യുക",
    govtVerifiedPortal: "ഗവണ്മെന്റ് അംഗീകൃത പോർട്ടൽ",
    selectMandi: "മാർക്കറ്റ് / കേന്ദ്രം തിരഞ്ഞെടുക്കുക",
    selectCrop: "വിള തരം തിരഞ്ഞെടുക്കുക",
    quantityUnit: "അളവും യൂണിറ്റും",
    unitQuintals: "ക്വിന്റൽ (100kg)",
    unitMT: "മെട്രിക് ടൺ (MT)",
    unitBags: "ചാക്ക് (50kg)",
    unitKg: "കിലോഗ്രാം (Kg)",
    vehicleType: "വാഹനം",
    vehicleNo: "വാഹന നമ്പർ",
    selectDate: "തീയതി",
    selectTimeSlot: "സമയം",
    slotCapacity: "ക്യൂ തിരക്ക് നില",
    confirmBooking: "🎟️ സ്ലോട്ട് ഉറപ്പാക്കുക & QR ടോക്കൺ നേടുക",
    benefitsTitle: "⚡ ഓൺലൈൻ ബുക്കിംഗ് നേട്ടങ്ങൾ",
    noLongLinesTitle: "നീണ്ട ക്യൂ ഒഴിവാക്കാം",
    noLongLinesText: "ബുക്ക് ചെയ്ത സമയത്ത് വരാം; മണിക്കൂറുകൾ കാത്തുനിൽക്കേണ്ടതില്ല.",
    guaranteedGovtRateTitle: "ഉറപ്പുള്ള സർക്കാർ നിരക്ക്",
    guaranteedGovtRateText: "ഇടനിലക്കാരില്ലാതെ മുഴുവൻ തറവിലയും നേടാം.",
    standardizedWeightingTitle: "കൃത്യമായ തൂക്കം",
    standardizedWeightingText: "ഡിജിറ്റൽ സംവിധാനം വഴി സുതാര്യമായ തൂക്കം.",
    directBankTransferTitle: "ബാങ്ക് അക്കൗണ്ടിലേക്ക് നേരിട്ട്",
    directBankTransferText: "24-48 മണിക്കൂറിനുള്ളിൽ പണം ബാങ്ക് അക്കൗണ്ടിൽ എത്തുന്നു.",
    sellerNameLabel: "കർഷകന്റെ / വിൽപ്പനക്കാരന്റെ പേര്",
    sellerNamePlaceholder: "മുഴുവൻ പേര് നൽകുക (ഉദാ: രമേഷ് കുമാർ)",
    welcomeModalTitle: "ഉഴവർ മുറ്റത്തിലേക്ക് സ്വാഗതം",
    welcomeModalSubtitle: "തമിഴ്‌നാട് സ്മാർട്ട് അഗ്രികൾച്ചർ പോർട്ടൽ",
    enterGuestBtn: "🌱 ലോഗിൻ ചെയ്യാതെ തുടരുക (ഗസ്റ്റ് മോഡ്)",
    loginRegisterBtn: "🔑 അക്കൗണ്ട് ലോഗിൻ / രജിസ്റ്റർ",
    guestNotice: "ഗസ്റ്റ് മോഡിൽ നിങ്ങൾക്ക് മാർക്കറ്റ് നിരക്കുകളും സ്ലോട്ട് ബുക്കിംഗും എളുപ്പത്തിൽ കാണാം.",
    offlineMode: "⚡ ഓഫ്‌ലൈൻ മോഡ്",
    mobileSmsAlertsTitle: "SMS അലേർട്ട്",
    sendBtn: "അയക്കുക",
    chatPlaceholder: "വിവരങ്ങൾക്ക് ചോദിക്കൂ...",
    catAll: "എല്ലാ വിളകളും",
    catCereals: "ധാന്യങ്ങൾ",
    catPulses: "പയർവർഗ്ഗങ്ങൾ",
    catOilseeds: "എണ്ണക്കുരുക്കൾ",
    catSpices: "സുഗന്ധവ്യഞ്ജനനങ്ങൾ",
    catVegetables: "പച്ചക്കറികൾ & പഴങ്ങൾ",
    catCashCrops: "നാണ്യവിളകൾ",
    gateEntry: "ഗേറ്റ് പ്രവേശനം സ്ഥിരീകരിച്ചു",
    qualityTesting: "ഗുണനിലവാര പരിശോധന പൂർത്തിയായി",
    weightScales: "തൂക്കം രേഖപ്പെടുത്തി",
    paymentsSent: "പണം അക്കൗണ്ടിൽ എത്തി",
    searchMarketPlaceholder: "വിളയോ വിപണിയോ തിരയുക...",
    welcomeText: "ഉഴവർ മുറ്റത്തിലേക്ക് സ്വാഗതം. വിൽ്പന സ്ലോട് ബുക്ക് ചെയ്യാം, തത്സമയ വിലയ്മാറുകൾ കാണാം, സ്റ്റോക്‌യാർഡ് സൂകഷിക്കാം, ക്വയൂ ടോകൺ ട്രാക് ചെയ്യാം.",
    activeAuctions: "സജീവനാലുള്ള ലലിതമുകൾ",
    myBids: "എന്റെ ബിഡ്സ്",
    escrowBalance: "എസ്ക്രോ ബാലങ്സ്",
    stockyardContracts: "സ്റ്റോക്‌യാർഡ് കരാർക൳ഺ്‌"
  },
  kn: {
    appTitle: "ಉಳವರ್ ಮುಟ್ರಮ್ (Uzhavar Mutram)",
    tagline: "ತಮಿಳುನಾಡು ಕೃಷಿ ಮಾರುಕಟ್ಟೆ ಮತ್ತು ಸ್ಮಾರ್ಟ್ ಕ್ಯೂ ವ್ಯವಸ್ಥೆ",
    farmerPortal: "ರೈತ ಪೋರ್ಟಲ್",
    officerPortal: "ಮಾರುಕಟ್ಟೆ ಅಧಿಕಾರಿ ಅಡ್ಮಿನ್",
    buyerPortal: "ಸಗಟು ખરીದಿದಾರ",
    kioskPortal: "ಪ್ರದರ್ಶನ ಮಂಡಳಿ",
    switchAccount: "ಲಾಗಿನ್ / ಖಾತೆ ಬದಲಿಸಿ",
    audioHelper: "🔊 ಧ್ವನಿ ಸಹಾಯ",
    voiceCommandEngine: "🎙️ ವಾಯ್ಸ್ ಕಮಾಂಡ್ ಎಂಜಿನ್",
    bookSlot: "ಮಾರಾಟ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ",
    queueTracker: "ಲೈವ್ ಕ್ಯೂ ಟ್ರ್ಯಾಕರ್",
    marketPrices: "📈 ಮಾರುಕಟ್ಟೆ ದರಗಳು",
    stockyard: "🏭 ಗೋದಾಮು ಶೇಖರಣೆ ಬಾಡಿಗೆ",
    myPasses: "ನನ್ನ ಪಾಸ್‌ಗಳು & ರಸೀದಿಗಳು",
    mspRates: "ಸರ್ಕಾರಿ ಬೆಂಬಲ ಬೆಲೆ (MSP)",
    profile: "ಬ್ಯಾಂಕ್ ವಿವರ & Aadhaar eKYC",
    customerCare: "📞 ಗ್ರಾಹಕ ಬೆಂಬಲ",
    bookSlotTitle: "ಬೆಳೆ ಮಾರಾಟ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ",
    govtVerifiedPortal: "ಸರ್ಕಾರದ ದೃಢೀಕೃತ ಪೋರ್ಟಲ್",
    selectMandi: "ಮಾರುಕಟ್ಟೆ / ಸಂಗ್ರಹಣಾ ಕೇಂದ್ರ ಆಯ್ಕೆಮಾಡಿ",
    selectCrop: "ಬೆಳೆ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
    quantityUnit: "ಪ್ರಮಾಣ ಮತ್ತು ಘಟಕ",
    unitQuintals: "ಕ್ವಿಂಟಾಲ್ (100kg)",
    unitMT: "ಮೆಟ್ರಿಕ್ ಟನ್ (MT)",
    unitBags: "ಚೀಲಗಳು (50kg)",
    unitKg: "ಕಿಲೋಗ್ರಾಂ (Kg)",
    vehicleType: "ವಾಹನ",
    vehicleNo: "ವಾಹನ ನೋಂದಣಿ ಸಂಖ್ಯೆ",
    selectDate: "ದಿನಾಂಕ",
    selectTimeSlot: "ಸಮಯದ ಸ್ಲಾಟ್",
    slotCapacity: "ಕ್ಯೂ ಸಾಮರ್ಥ್ಯ",
    confirmBooking: "🎟️ ಸ್ಲಾಟ್ ಖಚಿತಪಡಿಸಿ QR ಟೋಕನ್ ಪಡೆಯಿರಿ",
    benefitsTitle: "⚡ ಆನ್‌ಲೈನ್ ಬುಕಿಂಗ್ ಅನುಕೂಲಗಳು",
    noLongLinesTitle: "ಉದ್ದದ ಸಾಲಿನಲ್ಲಿ ನಿಲ್ಲಬೇಕಿಲ್ಲ",
    noLongLinesText: "ನಿಗದಿತ ಸಮಯಕ್ಕೆ ಬನ್ನಿ; ಗಂಟೆಗಟ್ಟಲೆ ಕಾಯುವುದು ತಪ್ಪಿಸಿ.",
    guaranteedGovtRateTitle: "ಖಚಿತ ಸರ್ಕಾರಿ ಬೆಂಬಲ ಬೆಲೆ",
    guaranteedGovtRateText: "ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲದೆ ಪೂರ್ಣ ಬೆಲೆ ಪಡೆಯಿರಿ.",
    standardizedWeightingTitle: "ನಿಖರ ತೂಕ",
    standardizedWeightingText: "ಡಿಜಿಟಲ್ ಯಂತ್ರಗಳ ಮೂಲಕ ಪಾರದರ್ಶಕ ತೂಕ.",
    directBankTransferTitle: "ನೇರ ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ",
    directBankTransferText: "24-48 ಗಂಟೆಗಳಲ್ಲಿ ಹಣ ನೇರವಾಗಿ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಸೇರುತ್ತದೆ.",
    sellerNameLabel: "ರೈತ / ಮಾರಾಟಗಾರನ ಹೆಸರು",
    sellerNamePlaceholder: "ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ (ಉದಾ: ರಮೇಶ್ ಕುಮಾರ್)",
    welcomeModalTitle: "ಉಳವರ್ ಮುಟ್ರಮ್‌ಗೆ ಸ್ವಾಗತ",
    welcomeModalSubtitle: "ತಮಿಳುನಾಡು ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಪೋರ್ಟಲ್",
    enterGuestBtn: "🌱 ಲಾಗಿನ್ ಇಲ್ಲದೆ ಮುಂದುವರಿಯಿರಿ (ಗೆಸ್ಟ್ ಮೋಡ್)",
    loginRegisterBtn: "🔑 ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ / ನೋಂದಾಯಿಸಿ",
    guestNotice: "ಗೆಸ್ಟ್ ಮೋಡ್‌ನಲ್ಲಿ ನೀವು ಲೈವ್ ಬೆಲೆಗಳು, ಗೋದಾಮು ವಿವರ ಮತ್ತು ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಬಹುದು.",
    offlineMode: "⚡ ಆಫ್‌ಲೈನ್ ಮೋಡ್",
    mobileSmsAlertsTitle: "SMS ಅಲರ್ಟ್",
    sendBtn: "ಪಂಪಿಸಿ",
    chatPlaceholder: "ಸ್ಲಾಟ್ ಬುಕಿಂಗ್, ಬೆಲೆಗಳಿಗಾಗಿ ಕೇಳಿ...",
    catAll: "ಎಲ್ಲಾ ಬೆಳೆಗಳು",
    catCereals: "ಧಾನ್ಯಗಳು",
    catPulses: "ಕಾಳುಗಳು",
    catOilseeds: "ಎಣ್ಣೆಕಾಳುಗಳು",
    catSpices: "ಮಸಾಲೆ ಪದಾರ್ಥಗಳು",
    catVegetables: "ತರಕಾರಿ ಮತ್ತು ಹಣ್ಣುಗಳು",
    catCashCrops: "ವಾಣಿಜ್ಯ ಬೆಳೆಗಳು",
    gateEntry: "ಗೇಟ್ ಪ್ರವೇಶ ಖಚಿತವಾಗಿದೆ",
    qualityTesting: "ಗುಣಮಟ್ಟ ತಪಾಸಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ",
    weightScales: "ತೂಕ ನಮೂದಿಸಲಾಗಿದೆ",
    paymentsSent: "ಹಣ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗಿದೆ",
    searchMarketPlaceholder: "ಬೆಳೆ ಅಥವಾ ಮಾರುಕಟ್ಟೆ ಹುಡುಕಿ...",
    welcomeText: "ಉಝಾವರ್ ಮುತ್ರಮಗೆ ಸ್ವಾಗತ. ಬೆಳೆ ಮಾರಾಟಿ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಬಹುದು, ನೇರವಂತಿ ಮಾರುಕತೆಗಳನ್ನು ನೋಡಬಹುದು, ಸ್ಟಕ್‍ಯಾರ್ಡ್ ಸಂರඕ್ಷಿಸಿಕೊಳ್ಳಬಹುದು, ಕ್ಯೂ ಟೋಕನ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಬಹುದು.",
    activeAuctions: "ಸಕ್ರಿಯ ಹರಾರಗಳು",
    myBids: "ನನ್ನ ಬಿಡ್‌ಗಳು",
    escrowBalance: "ಎಸ್ಕ್ರೋ ಸಮತುಲ್ಯ",
    stockyardContracts: "ಸ್ಟಾಕ್‍ಯಾರ್ಡ್ ಒಪ್ಪಂದಗಳು"
  }
};
